### PR TITLE
Configure maven to populate the protocol buffer git submodule.

### PR DESCRIPTION
**Pull request by deflaux**
Fixes https://github.com/googlegenomics/utils-java/issues/107

### CODE REVIEW

**Comment by calbach** [comment]
Cool, thanks. LGTM

**Comment by dionloy** [comment]
LGTM

**Comment by pgrosu** [comment]
Hi CH and Dion,

Did you guys actually test Nicole's PR?  I'm getting a build error:

```
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] Building Google Genomics Utils 1.0.5
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO]
[INFO] [INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ google-genomics-utils ---
[INFO] [INFO]
[INFO] [INFO] --- exec-maven-plugin:1.5.0:exec (git submodule update) @ google-genomics-utils ---
[INFO] fatal: Not a git repository (or any of the parent directories): .git
[INFO] [ERROR] Command execution failed.
[INFO] org.apache.commons.exec.ExecuteException: Process exited with an error: 128 (Exit value: 128)
[INFO]  at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
[INFO]  at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
[INFO]  at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:764)
[INFO]  at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:711)
[INFO]  at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:289)
[INFO]  at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
[INFO]  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
[INFO]  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
[INFO]  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
[INFO]  at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
[INFO]  at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
[INFO]  at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
[INFO]  at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
[INFO]  at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
[INFO]  at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
[INFO]  at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
[INFO]  at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
[INFO]  at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
[INFO]  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO]  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO]  at java.lang.reflect.Method.invoke(Method.java:483)
[INFO]  at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[INFO]  at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[INFO]  at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[INFO]  at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] BUILD FAILURE
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] Total time: 1.879 s
[INFO] [INFO] Finished at: 2016-07-14T13:27:24-05:00
[INFO] [INFO] Final Memory: 10M/1062M
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:exec (git submodule update) on project google-genomics-utils: Command execution failed. Process exited with an error: 128 (Exit value: 128) -> [Help 1]
[INFO] [ERROR]
[INFO] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[INFO] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
[INFO] [ERROR]
[INFO] [ERROR] For more information about the errors and possible solutions, please read the following articles:
[INFO] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.540 s
[INFO] Finished at: 2016-07-14T13:27:28-05:00
[INFO] Final Memory: 9M/1057M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5:prepare (default-cli) on project google-genomics-utils: Maven execution failed, exit code: '1' -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by dionloy** [comment]
Nope, I don't patch and test PRs. Travis seems to have been happy though
(Nicole, that seems unexpected?).

**Comment by deflaux** [comment]
@pgrosu What was your maven command line that yielded that error?

**Comment by pgrosu** [comment]
@deflaux I tested it with both of the following:

```
mvn release:prepare && mvn release:perform
```
and
```
mvn package
```



~p

**Comment by pgrosu** [comment]
@dionloy Travis has another failure but that's related to Coveralls:

```
[INFO] Writing Coveralls data to /home/travis/build/googlegenomics/utils-java/target/coveralls.json from coverage report /home/travis/build/googlegenomics/utils-java/target/site/cobertura/coverage.xml
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:22 min
[INFO] Finished at: 2016-07-13T22:20:37+00:00
[INFO] Final Memory: 44M/376M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eluder.coveralls:coveralls-maven-plugin:2.2.0:cobertura (default-cli) on project google-genomics-utils: Build error: Could not find source file com/google/api/AnnotationsProto.java from any source directory or source url. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

It is near the end of the log file here:

https://s3.amazonaws.com/archive.travis-ci.org/jobs/144596670/log.txt

**Comment by deflaux** [comment]
@pgrosu The error you have is `fatal: Not a git repository (or any of the parent directories): .git`

Did you:
```
git clone git@github.com:deflaux/utils-java.git
cd utils-java
mvn package
```

If it was from `mvn release:perform` instead, that is the issue I'm actively trying to fix, so it may not yet be correct.  I haven't yet found a good way to test it without actually trying to do a release.

**Comment by pgrosu** [comment]
@deflaux I used the zip download file but via clone l get an error of denial:

```
$ git clone git@github.com:deflaux/utils-java.git
Initialized empty Git repository in /home/pgrosu/me/gg_utils/nicole-test-clone/utils-java/.git/
Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
Permission denied (publickey).
fatal: The remote end hung up unexpectedly
[pgrosu@eofe4 nicole-test-clone]$ cd utils-java
-bash: cd: utils-java: No such file or directory
[pgrosu@eofe4 nicole-test-clone]$ mvn package
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.992 s
[INFO] Finished at: 2016-07-14T14:04:36-05:00
[INFO] Final Memory: 4M/1036M
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/home/pgrosu/me/gg_utils/nicole-test-clone). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException
$
```

**Comment by deflaux** [comment]
@pgrosu for clone, sounds like you just need the https link instead of ssh:
```
git clone https://github.com/deflaux/utils-java.git
cd utils-java
mvn package
```

For the zip, that error makes sense since the zip isn't a git repo.  I added an activation profile to that plugin.  Thanks!

**Comment by calbach** [comment]
lgtm

**Comment by pgrosu** [comment]
@deflaux The good news is that the clone now works!  Thank you :)

Regarding zip files, they work unless there are submodule updates that are required.  So since PRs are based on commits, it's possible to actually get the zip of any commit, which for this PR the original commit could retrieved at the following location:

https://github.com/deflaux/utils-java/tree/53df562c921a244defbe7b6435aeea9ee14d01f0

The new commit would be the following:

https://github.com/deflaux/utils-java/tree/6c1513933767ac31129578254b42e36a6d43b8a2

On the right-hand side there is a **[Clone or Download]** button, and to get the specific ZIP file that represents the commit for the repository, it would be the following:

https://codeload.github.com/deflaux/utils-java/zip/6c1513933767ac31129578254b42e36a6d43b8a2

This link will initiate a ZIP download.

If you download that, the `pom.xml` files are the same - including the rest of the files.  The only difference between the two is that one has a `.git` directory and the other does not - all the rest is the same.  If I copy the `.git` directory from the clone then it works.

Now if the `.git` is missing, it probably would be good to print a comment that a `git clone` is a prerequisite.  It should be possible to include in the `pom.xml` a check in that if the `.git` directory does not exist, it can be easily recreated - including all the subdirectories and files - or via a self-update through another `exec-maven-plugin`, but that would be too many checks and there are more interesting problems to work on :)

I think for now the using `https://github.com/deflaux/utils-java.git` with `mvn package` is a good process by which to check without performing a release.  There are many way to test if the Jar is working properly.  

It would be good to include a build option to bundle so that everything is in one Jar file.

Thank you for the help,
Paul

**Pull request merged**
