### PR TITLE
Combining all read conversion utils to ReadUtils in utils-java.

### PR DESCRIPTION
**Pull request by davidadamsphd**
I'm copying/moving GenomicsConverter from googlegenomics/gatk-tools-java
and ReadUtils from googlegenomics/utils-java.

This is the first step of a multi-step process
(1) Copy the utils to utils-java
(2) Bump the version of utils-java
(3) Update gatk-tools-java
(4) utils-java

I've moved the code basically "as-is." Let me know if anything should to be changed.

### CODE REVIEW

**Comment by deflaux** [comment]
LGTM assuming all tests pass for all the refactored repos, thanks @davidadamsphd

**Comment by iliat** [comment]
LGTM, since the paths are slightly different than where these used to be in gatk-tools-java, it should not clash with the code in gatk-tools-java but just in case it would be good to make sure it still builds fine.

**Comment by iliat** [comment]
@davidadamsphd 
Oh, and are you going to also copy https://github.com/googlegenomics/dataflow-java/blob/1f0ca31869c336bc7fb72b2176f4c27de83e6e54/src/main/java/com/google/cloud/genomics/dataflow/readers/bam/ReadConverter.java or is it in a separate PR ?

**Comment by davidadamsphd** [comment]
@iliat, both getAttr() and makeRead() are in *this* PR.

**Comment by iliat** [comment]
@davidadamsphd Gah! Indeed :) Sorry, I think I scrolled passed it. LGTM.

**Comment by davidadamsphd** [comment]
The tests pass in the refactored repos, merging.

**Pull request merged**
