### PR TITLE
Bump grpc-java.

### PR DESCRIPTION
**Pull request by deflaux**

### CODE REVIEW

**Comment by calbach** [comment]
Do you need to bump the protoc plugin version as well?

```
         <!--
           The version of protoc must match protobuf-java. If you don't depend on
           protobuf-java directly, you will be transitively depending on the
           protobuf-java version that grpc depends on.
         -->
         <protocArtifact>com.google.protobuf:protoc:3.0.0-beta-2:exe:${os.detected.classifier}</protocArtifact>
         <pluginId>grpc-java</pluginId>
         <pluginArtifact>io.grpc:protoc-gen-grpc-java:0.12.0:exe:${os.detected.classifier}</pluginArtifact>
```

**Comment by deflaux** [comment]
Thanks @calbach , fixed that additional bump.

From https://groups.google.com/forum/#!topic/grpc-io/dA_n3AuN8Jw 
"Now depending against protobuf-3.0.0-beta-2, protobuf-nano-3.0.0-alpha-5, and netty-4.1.0.CR1"

**Comment by calbach** [comment]
LGTM

**Comment by pgrosu** [comment]
Maybe the `google.api.genomics.version` would might need to also be updated to `v1-rev59-1.21.0` from `v1beta2-rev25-1.19.1` - at the following line:

https://github.com/googlegenomics/utils-java/blob/7663b72e62d1bed8d71e7ec44cc2dd7e293d662d/pom.xml#L298

It seems to be referenced via `${google.api.genomics.version}`.

~p

**Pull request merged**
