### PR TITLE
Fixing auth for gRPC to get credentials from .json file.

### PR DESCRIPTION
**Pull request by iliat**

### CODE REVIEW

**Comment by deflaux** [comment]
Thanks for the fix!

Please update it to client_secrets.json so that it is consistent with all our other samples and then LGTM.

**Comment by iliat** [comment]
@deflaux PTAL: This is the simplest code I could throw together to get the credentials but if there is a simpler way please let me know. 
I have to say that having both XXXCredential and XXXCredentials classes makes auth stuff pretty confusing :)

**Comment by deflaux** [comment]
@mbrukman we see your doc about auth and grpc https://github.com/grpc/grpc-common/blob/master/grpc-auth-support.md but can you point us to a tiny sample that also takes the user through an oauth2 flow?

We are currently mixing the use of https://github.com/google/google-auth-library-java and https://developers.google.com/api-client-library/java/google-api-java-client/oauth2 and hoping to simplify it further.
```
import com.google.api.client.auth.oauth2.Credential;
import com.google.auth.oauth2.GoogleCredentials;
import com.google.auth.oauth2.UserCredentials;
```

**Comment by ssgross** [comment]
I guess default creds no longer work due to visibility configuration?

Have you tried this:

https://github.com/google/google-auth-library-java/blob/master/oauth2_http/java/com/google/auth/oauth2/GoogleCredentials.java#L67

with a service account key file? If that works you might also try "gcloud auth activate-service-account" in combination with default creds.

**Comment by mbrukman** [comment]
@deflaux — sorry, I didn't write 
[https://github.com/grpc/grpc-common/blob/master/grpc-auth-support.md](grpc-auth-support.md), I only submitted a few fixes to it. Please see the [doc's history](https://github.com/grpc/grpc-common/commits/master/grpc-auth-support.md) for a list of folks who've made much larger contributions.

**Comment by iliat** [comment]
@ssgross Yeah, I had it working with a service acct but Nicole wanted something that works with regular client credentials (and I agree).

**Comment by anthmgoogle** [comment]
In the very short term this is unfortunately about the simplest way to use 3LO with gRPC for Java. It is acknowledged that the mixture of these two sets of libraries is not what we want going forward. There is a work item in progress that will add 3LO functionality to google-auth-library-java that should be available before the end of July.

**Comment by deflaux** [comment]
Thanks for the sanity check @anthmgoogle 

@iliat LGTM and thank you!

**Pull request merged**
