### PR TITLE
rm generated gRPC code and protos in favor of a Git submodule

### PR DESCRIPTION
**Pull request by calbach**
Note: now always compiles from proto.

### CODE REVIEW

**Comment by deflaux** [comment]
LGTM but the README.md needs a corresponding update.  Do you want to add that to this PR or do you want me to take care of it and merge both PRs at the same time?

**Comment by calbach** [comment]
Thanks, good catch - updated the PR to include updates to the README. PTAL.

**Comment by deflaux** [comment]
LGTM

**Comment by pgrosu** [comment]
Probably the Maven build instructions would also need to be updated to the following, in the [Readme documentation](https://github.com/googlegenomics/utils-java/blob/master/README.md):

```
git clone --depth=50 https://github.com/googlegenomics/utils-java.git
cd utils-java
git submodule update --init --recursive
mvn package
```

Since the current method ends in errors:

```
$ git clone https://github.com/googlegenomics/utils-java
$ cd utils-java
$ mvn package
...
[ERROR] location: class com.google.cloud.genomics.utils.grpc.ReadStreamIterator
[ERROR] /home/pgrosu/me/gg_utils/build_test/utils-java/src/main/java/com/google/cloud/genomics/utils/grpc/ReadStreamIterator.java:[117,3] cannot find symbol
[ERROR] symbol:   class StreamReadsRequest
[ERROR] location: class com.google.cloud.genomics.utils.grpc.ReadStreamIterator
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
$
```

**Comment by calbach** [comment]
Thanks, good catch. Sent https://github.com/googlegenomics/utils-java/pull/97

**Comment by pgrosu** [comment]
Sure thing, and thanks for the update.

Hope you have a good weekend!
~p

**Pull request merged**
